#!/bin/python3

# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143?

def largestPrime(n, primedict):
    '''
    Find the largest prime factor of number n.
    @param n - the value of which factors we are looking for
    @primedict - dictionary with cached prime numbers
    '''
    if n in primedict:
        return primedict[n]
    largestfactor = 0
    # find divisors
    i = 2
    initial_n = n
    while i <= (int(initial_n**0.5 + 0.3)) :
        # check if divisible
        if n % i == 0:
            largestfactor = i
            n = int(n / i)
            # check dictionary
            if n in primedict:
                largestfactor = primedict[n]
                primedict[initial_n] = largestfactor
                return largestfactor
        else:
            i += 1
    if n > largestfactor:
        largestfactor = n
    primedict[initial_n] = largestfactor
    return largestfactor
    
if __name__ == '__main__':
  print(largestPrime(600851475143, {}))
